### ISSUE TITLE
Mirrors with @angular/material & 'complex' template

### ISSUE THREAD

**Issue by mildful** [valor-software/ng2-dragula#540]
Hi, first of all, thanks for this tool.

I'm using it with `@angular/material` :

```html
    <md-list #root
             [dragula]="'bag'"
             [dragulaModel]="contentMedias">
      <md-list-item class="paneItem" *ngFor="let media of contentMedias">
        <md-icon md-list-avatar>delete</md-icon>
        <h3 md-line> Basic example </h3>
        <p md-line>
          <span class="session"> Just a line </span>
        </p>
        <!-- ... other things ... -->
      </md-list-item>
    </md-list>
```

I'm facing a little issue (maybe am I doind wrong ?). When dragging a `md-list-item`, the mirror created by dragula seems to doesn't keep the associated styles.

An obvious way to solve this is to disable component encapsulation : `encapsulation: ViewEncapsulation.None` and write by hand the style of @angular/material :

```css
@import '../../../variables';

// something like that : (ugly)

.pane-item.gu-mirror {
   display: block;
   color: black;
   background: #F0F0F0;
   border-radius: 3px;

   h3 {
      font-size: 16px !important;
   }

   md-icon {
      background-repeat: no-repeat;
      display: inline-block;
      fill: currentColor;

      font-family: 'Material Icons';
      font-weight: normal;
      font-style: normal;
      font-size: 24px;
      line-height: 1;
      letter-spacing: normal;
      text-transform: none;
      display: inline-block;
      white-space: nowrap;
      word-wrap: normal;
      direction: ltr;
      -webkit-font-feature-settings: 'liga';
      -webkit-font-smoothing: antialiased;

      flex-shrink: 0;
      width: 40px;
      height: 40px;
      border-radius: 50%;
   }
   .md-list-text {
      display: flex;
      flex-direction: column;
      width: 100%;
      box-sizing: border-box;
      overflow: hidden;
      padding: 0 16px;
      font-size: 16px !important;

      [md-line] {
         white-space: nowrap;
         overflow-x: hidden;
         text-overflow: ellipsis;
         display: block;
         box-sizing: border-box;
         margin: 0;
         padding: 0;
         font-weight: 400;
         font-size: 16px !important;
      }
   }
   .md-list-item {
      display: flex;
      flex-direction: row;
      align-items: center;
      font-family: Roboto,"Helvetica Neue",sans-serif;
      box-sizing: border-box;
      font-size: 16px;
      height: 72px;
      padding: 0 16px;
   }
}
```

Of course, this is not a viable solution.
