### ISSUE TITLE
Customising .gu-mirror to include extra content

### ISSUE THREAD

**Issue by ankurshah32** [valor-software/ng2-dragula#705]
Whenever we are dragging any dom element it creates an image of what we are dragging shows image at mouse pointer. I have a requirement that i need to add tool tip to this image? How can we achieve this?

**Comment by ankurshah32** [comment]
if you can give me an example. That will be helpful. As i was trying showing and hiding the div but it is not a good approach for me because I am dragging one of the tree node to another tree-node while moving from one tree node to another i have pass through many tree node div show and hide for each and every node. it looks bad in my case

**Comment by cormacrelf** [comment]
Ok, so first up, it's **not an image**. It's a clone of the original element, made to be position: fixed via the .gu-mirror class. You can style this clone as with any other element. Try opening the inspector and looking at the bottom of the `<body>` tag; when you drag something, it will appear there.

So, with:

```html
<div class="parent">
  <div class="child">
    <div class="tooltip">tooltip content 1</div>
    child content 1
  </div>
  <div class="child">
    <div class="tooltip">tooltip content 2</div>
    child content 2
  </div>
</div>
```

and CSS:

```css
.child {
  background-color: white;
  height: 300px;
  width: 400px;
  position: relative;
}

// make it sit at the bottom left, outside the .child
.child .tooltip {
  position: absolute;
  height: 24px;
  left: 0;
  bottom: -24px;
  background-color: yellow;
}

// the good part
.child:not(.gu-mirror) .tooltip {
  display: none;
}
```

... the tooltip will be hidden except inside the mirrored clone.
